<a href="https://colab.research.google.com/github/sanmaykant/sec/blob/main/Notebooks/topic_modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install bertopic umap-learn hdbscan

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: umap-learn in /usr/local/lib/python3.12/dist-packages (0.5.11)
Requirement already satisfied: hdbscan in /usr/local/lib/python3.12/dist-packages (0.8.42)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.3.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (1.16.3)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.6.0)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.8.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.10.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.24.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 3.8 MB/s eta 0:00:00
Installing collected packages: bertopic
Successfully installed bertopic-0.17.4

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

BASE_PATH = "/content/drive/MyDrive/sec-risk-analyzer"

EMBED_PATH = os.path.join(BASE_PATH, "data/embeddings")
MODEL_PATH = os.path.join(BASE_PATH, "models")
ARTIFACT_PATH = os.path.join(BASE_PATH, "artifacts/topic_data")

os.makedirs(MODEL_PATH, exist_ok=True)
os.makedirs(ARTIFACT_PATH, exist_ok=True)

print("Paths ready!")

Paths ready!

In [ ]:
import numpy as np
import json

embeddings = np.load(os.path.join(EMBED_PATH, "all_embeddings.npy"))

with open(os.path.join(EMBED_PATH, "metadata.json"), "r") as f:
    metadata = json.load(f)

with open(os.path.join(BASE_PATH, "data/processed/chunks/all_chunks.json"), "r") as f:
    chunk_data = json.load(f)

docs = chunk_data["chunks"]

print("Docs:", len(docs))
print("Embeddings:", embeddings.shape)

Docs: 1649
Embeddings: (1649, 768)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
)

In [ ]:
from bertopic import BERTopic

topic_model = BERTopic(
    vectorizer_model=vectorizer_model,
    calculate_probabilities=True,
    verbose=True
)

topics, probs = topic_model.fit_transform(docs, embeddings)

2026-04-13 15:21:43,867 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-04-13 15:21:53,975 - BERTopic - Dimensionality - Completed ✓
2026-04-13 15:21:53,977 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-04-13 15:21:54,300 - BERTopic - Cluster - Completed ✓
2026-04-13 15:21:54,307 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-04-13 15:21:54,689 - BERTopic - Representation - Completed ✓

In [ ]:
topics_full = topics.copy()

In [ ]:
topic_info = topic_model.get_topic_info()
topic_info.head(10)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,108,-1_company_investigations_regulations_companys,"[company, investigations, regulations, company...",[The People’s Republic of China (“PRC”) and In...
1,0,71,0_tax_taxes_tax rate_effective tax,"[tax, taxes, tax rate, effective tax, rate, ef...",[The tax regimes we are subject to or operate ...
2,1,67,1_acquisitions_strategic_transactions_acquire,"[acquisitions, strategic, transactions, acquir...","[We provide physical, e-commerce, and omnichan..."
3,2,52,2_laws_regulations_protection_data,"[laws, regulations, protection, data, content,...",[We have been subject to other significant leg...
4,3,52,3_ads_advertising_marketers_ability,"[ads, advertising, marketers, ability, effecti...",[•our ability to attract and retain marketers ...
5,4,51,4_payments_payment_card_money,"[payments, payment, card, money, subject, card...",[We accept payments using a variety of methods...
6,5,47,5_mobile_developers_signals_products,"[mobile, developers, signals, products, mobile...",[The substantial majority of our revenue is ge...
7,6,40,6_stock_changes_market_estimates,"[stock, changes, market, estimates, securities...",[We Have a Rapidly Evolving Business Model and...
8,7,39,7_products_users_engagement_products services,"[products, users, engagement, products service...",[•user behavior on any of our products changes...
9,8,38,8_extent_costs_ability_costs related,"[extent, costs, ability, costs related, relate...",[our ability to maintain gross margins and ope...

In [ ]:
for topic_id in topic_info["Topic"].head(10):
    print(f"\nTopic {topic_id}:")
    print(topic_model.get_topic(topic_id))

Topic -1:
[('company', np.float64(0.014089698353267914)), ('investigations', np.float64(0.011566945472617792)), ('regulations', np.float64(0.011099380021472784)), ('companys', np.float64(0.010728981355207277)), ('governance', np.float64(0.010289194756864567)), ('intellectual', np.float64(0.01025716184488836)), ('intellectual property', np.float64(0.01025716184488836)), ('government', np.float64(0.010195966610120701)), ('property', np.float64(0.010007888682673211)), ('prc', np.float64(0.009675584692473316))]

Topic 0:
[('tax', np.float64(0.08415347493202222)), ('taxes', np.float64(0.035100213895617176)), ('tax rate', np.float64(0.02680084241808706)), ('effective tax', np.float64(0.0250752718011818)), ('rate', np.float64(0.02285388725255445)), ('effective', np.float64(0.021808513547596806)), ('changes', np.float64(0.02087827470195172)), ('tax laws', np.float64(0.01945371822584187)), ('obligations', np.float64(0.018759244702705135)), ('income', np.float64(0.01863971466535115))]

Topic 1:
[('acquisitions', np.float64(0.03878400263942997)), ('strategic', np.float64(0.029244976390989132)), ('transactions', np.float64(0.020864232594779385)), ('acquire', np.float64(0.019453024030419114)), ('agreements', np.float64(0.018707143922963652)), ('strategic transactions', np.float64(0.018666277587574477)), ('difficulty', np.float64(0.017483984641141596)), ('companies', np.float64(0.01743067167299753)), ('acquisitions strategic', np.float64(0.016506088276710507)), ('businesses', np.float64(0.016444206180945584))]

Topic 2:
[('laws', np.float64(0.0195156347177467)), ('regulations', np.float64(0.01867748683044409)), ('protection', np.float64(0.018348507751805476)), ('data', np.float64(0.017957585462495068)), ('content', np.float64(0.016048485136239722)), ('european', np.float64(0.0160353320093593)), ('services', np.float64(0.015321174621779059)), ('states', np.float64(0.014239517427628995)), ('laws regulations', np.float64(0.013705318709328857)), ('privacy', np.float64(0.012957159129364841))]

Topic 3:
[('ads', np.float64(0.041752539603377437)), ('advertising', np.float64(0.03879766911876567)), ('marketers', np.float64(0.03221132415592648)), ('ability', np.float64(0.022720462287068595)), ('effectiveness', np.float64(0.018390204081965976)), ('changes', np.float64(0.01794221567841972)), ('products', np.float64(0.017747472190936777)), ('inability', np.float64(0.016054104550602025)), ('format', np.float64(0.015828713493199205)), ('measure effectiveness', np.float64(0.015699963492005642))]

Topic 4:
[('payments', np.float64(0.03742068887575009)), ('payment', np.float64(0.0270167070563857)), ('card', np.float64(0.02646169849390378)), ('money', np.float64(0.017601807268423517)), ('subject', np.float64(0.017015750436240522)), ('cards', np.float64(0.016921454894223833)), ('payment card', np.float64(0.016578606010526346)), ('requirements', np.float64(0.015477093957577154)), ('debit', np.float64(0.014831129283646962)), ('regulations', np.float64(0.014666879831976039))]

Topic 5:
[('mobile', np.float64(0.04532504237453903)), ('developers', np.float64(0.02885004815461124)), ('signals', np.float64(0.021774363681494168)), ('products', np.float64(0.020907500977581546)), ('mobile operating', np.float64(0.019735053616835647)), ('ads', np.float64(0.01752401238604602)), ('mobile devices', np.float64(0.016333626805402002)), ('use', np.float64(0.01627895684178502)), ('operating systems', np.float64(0.015853226017007827)), ('monetization', np.float64(0.015853226017007827))]

Topic 6:
[('stock', np.float64(0.02805942612842258)), ('changes', np.float64(0.024692784368902286)), ('market', np.float64(0.0229329348574954)), ('estimates', np.float64(0.02110609782359379)), ('securities analysts', np.float64(0.02044023701921983)), ('changes financial', np.float64(0.02044023701921983)), ('financial estimates', np.float64(0.02044023701921983)), ('analysts', np.float64(0.02044023701921983)), ('projections', np.float64(0.01956340637663591)), ('stock market', np.float64(0.019373280861860222))]

Topic 7:
[('products', np.float64(0.030942473272430156)), ('users', np.float64(0.02918417200768652)), ('engagement', np.float64(0.02332877830695828)), ('products services', np.float64(0.020157487338761288)), ('user', np.float64(0.019783069500819546)), ('mobile', np.float64(0.0183102125420966)), ('engaging', np.float64(0.017689927591357145)), ('content', np.float64(0.017534651928386435)), ('services', np.float64(0.016743861275916882)), ('unable', np.float64(0.01568639150083767))]

Topic 8:
[('extent', np.float64(0.024570680574317372)), ('costs', np.float64(0.02348769570186089)), ('ability', np.float64(0.019253238414589816)), ('costs related', np.float64(0.018550609696135246)), ('related', np.float64(0.016105818667703192)), ('including', np.float64(0.015070046461367066)), ('products', np.float64(0.014184287778354232)), ('expense', np.float64(0.01329817012195375)), ('centers technical', np.float64(0.013278191563321037)), ('including costs', np.float64(0.013278191563321037))]

In [ ]:
topic_info_clean = topic_info[topic_info["Topic"] != -1]
topic_info_clean.head()

,Topic,Count,Name,Representation,Representative_Docs
1,0,71,0_tax_taxes_tax rate_effective tax,"[tax, taxes, tax rate, effective tax, rate, ef...",[The tax regimes we are subject to or operate ...
2,1,67,1_acquisitions_strategic_transactions_acquire,"[acquisitions, strategic, transactions, acquir...","[We provide physical, e-commerce, and omnichan..."
3,2,52,2_laws_regulations_protection_data,"[laws, regulations, protection, data, content,...",[We have been subject to other significant leg...
4,3,52,3_ads_advertising_marketers_ability,"[ads, advertising, marketers, ability, effecti...",[•our ability to attract and retain marketers ...
5,4,51,4_payments_payment_card_money,"[payments, payment, card, money, subject, card...",[We accept payments using a variety of methods...

In [ ]:
enriched_data = []

for i in range(len(docs)):
    enriched_data.append({
        "chunk": docs[i],
        "topic": int(topics[i]),
        "year": metadata[i]["year"],
        "ticker": metadata[i]["ticker"]
    })

print("Enriched dataset ready!")

Enriched dataset ready!

In [ ]:
topic_model.save(os.path.join(MODEL_PATH, "bertopic_model"))
print("Model saved!")

2026-04-13 15:19:04,914 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Model saved!

In [ ]:
import json

with open(os.path.join(ARTIFACT_PATH, "enriched_chunks.json"), "w") as f:
    json.dump(enriched_data, f)

print("Enriched data saved!")

Enriched data saved!

In [ ]:
import numpy as np
topic_embeddings = topic_model.topic_embeddings_
np.save(os.path.join(ARTIFACT_PATH, "topic_embeddings.npy"), topic_embeddings)

print("Topic embeddings saved!")

Topic embeddings saved!

In [ ]:
topic_info.to_csv(os.path.join(ARTIFACT_PATH, "topic_info.csv"), index=False)
print("Topic info saved!")

Topic info saved!

In [ ]:
topic_model_reduced = topic_model.reduce_topics(docs, nr_topics=20)
topics_reduced = topic_model.topics_

2026-04-13 15:22:25,570 - BERTopic - Topic reduction - Reducing number of topics
2026-04-13 15:22:25,618 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-04-13 15:22:26,727 - BERTopic - Representation - Completed ✓
2026-04-13 15:22:26,733 - BERTopic - Topic reduction - Reduced number of topics from 64 to 20

In [ ]:
topic_model.save(os.path.join(MODEL_PATH, "bertopic_model_reduced"))
with open(os.path.join(ARTIFACT_PATH, "topics_reduced.json"), "w") as f:
    json.dump(topics_reduced, f)

print("Reduced model saved!")

2026-04-13 15:22:35,806 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Reduced model saved!

In [ ]:
# Analysis

In [ ]:
from collections import defaultdict
year_topics = defaultdict(set)

for item in enriched_data:
    if item["topic"] != -1:
        year_topics[item["year"]].add(item["topic"])

for year in sorted(year_topics):
    print(year, "→", len(year_topics[year]), "topics")

2020 → 65 topics
2021 → 65 topics
2022 → 65 topics
2023 → 65 topics
2024 → 65 topics

In [ ]:
company_topics = defaultdict(set)

for item in enriched_data:
    if item["topic"] != -1:
        company_topics[item["ticker"]].add(item["topic"])

for comp in company_topics:
    print(comp, "→", len(company_topics[comp]), "topics")

AAPL → 34 topics
META → 48 topics
AMZN → 24 topics

In [ ]:
topic_model.visualize_topics()

In [ ]:
topic_model.visualize_hierarchy()